# Generated by Django 4.1.3 on 2023-01-24 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c4a259e6-f30c-4569-a1c6-f003f59ab2bd'), help_text='Unique ID for this particular blog', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter the description of this blog', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a blog type(e.g. Celebrity Gist)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('277111de-8f09-4f93-b148-0625937286dd'), help_text='Unique ID for this particular comment', primary_key=True, serialize=False)),
                ('written_date', models.DateField(auto_now=True, null=True, verbose_name=datetime.datetime)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blog')),
            ],
            options={
                'ordering': ['written_date'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ManyToManyField(help_text='Select a type for this blog', to='blog.blogtype'),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.writer'),
        ),
    ]
