# Generated by Django 4.1.3 on 2023-01-25 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c52298f6-c25d-4548-a986-fa2a941b7da3'), help_text='Unique ID for this particular blog', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('581f4ce1-c9e7-4320-a706-020f2d4da468'), help_text='Unique ID for this particular comment', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('F', 'Food'), ('T', 'Travel'), ('H', 'Health'), ('L', 'Lifestyle'), ('FB', 'Fashion & Beauty'), ('PH', 'Photography'), ('P', 'Personal'), ('DC', 'DIY Craft')], default='P', help_text='Select a type for this blog', max_length=2),
        ),
    ]
