# Generated by Django 4.1.3 on 2023-01-28 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24eabb12-dbf5-480d-8990-30cb9bf5808f'), help_text='Unique ID for this particular comment', primary_key=True, serialize=False),
        ),
    ]
